{{- define "nacos.configmap.nacos.sql.v1" -}}
{{ .Files.Get "flyway/V1__nacos-mysql.sql" }}
{{- end }}
{{- $fullname := include "nacos.fullname" . -}}
{{- if eq .Values.nacos.storage.type "mysql" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}-configmap
  namespace: {{ .Values.namespace }}
data:
  {{- with .Values.nacos.storage.db }}
  mysql.db.host: {{ .host }}
  mysql.db.name: {{ .name }}
  mysql.port: {{ .port | default 3306 | quote }}
  mysql.param: {{ .param | default "characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false" }}
  {{- end}}
  V1__nacos-mysql.sql: |-
    {{- include "nacos.configmap.nacos.sql.v1" . | nindent 4 }}
{{- end }}
