{{- $fullname := include "nacos.fullname" . -}}
{{- define "nacos.secret.flyway.conf" -}}
{{- with .Values.nacos.storage.db -}}
flyway.url=jdbc:mysql://{{ .host }}:{{ .port | default 3306 }}/{{ .name }}?{{ .param | default "characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false" }}
flyway.user={{ .username }}
flyway.password={{ .password }}
{{- end -}}
{{- end }}
{{- if eq .Values.nacos.storage.type "mysql" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-secret
  namespace: {{ .Values.namespace }}
data:
  {{- with .Values.nacos.storage.db }}
  mysql.user: {{ .username | b64enc }}
  mysql.password: {{ .password | b64enc }}
  {{- end }}
  {{- if .Values.nacos.plugin.flyway.enable }}
  flyway.conf: {{ include "nacos.secret.flyway.conf" . | b64enc }}
  {{- end }}
{{- end }}
