{{- $name := include "nacos.name" . -}}
{{- if eq .Values.nacos.storage.type "mysql" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-secret
  namespace: {{ .Values.namespace }}
data:
  {{- with .Values.nacos.storage.db }}
  mysql.user: {{ .username | b64enc }}
  mysql.password: {{ .password | b64enc }}
  {{- end }}
{{- end }}
