{{- $fullname := include "xxljob.fullname" . -}}
{{- define "xxljob.secret.flyway.conf" -}}
{{- with .Values.xxljob.storage.db -}}
flyway.url=jdbc:mysql://{{ .host }}:{{ .port | default 3306 }}/{{ .name }}?{{ .param | default "characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false" }}
flyway.user={{ .username }}
flyway.password={{ .password }}
{{- end -}}
{{- end }}
{{- define "xxljob.secret.xxljob.params" -}}
{{- with .Values.xxljob.storage.db -}}
--spring.datasource.url=jdbc:mysql://{{ .host }}:{{ .port | default 3306 }}/{{ .name }}?{{ .param | default "characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false" }}
--spring.datasource.username={{ .username }}
--spring.datasource.password={{ .password }}
{{- end -}}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-secret
  namespace: {{ .Values.namespace }}
data:
  xxljob.params: {{ include "xxljob.secret.xxljob.params" . | replace "\n" " " | b64enc }}
  {{- if .Values.xxljob.plugin.flyway.enable }}
  flyway.conf: {{ include "xxljob.secret.flyway.conf" . | b64enc }}
  {{- end }}
